document.getElementById('SuperHeader').style.display='none';//remove covid and shop link
document.getElementById('HeaderComponent').style.display='none';//remove literotica button
document.querySelector('.SAAWidget__container').style.display='none';//remove webcam pictures
document.querySelector('.a_a').style.display='none';//remove cams try out
document.getElementsByClassName("clearfix u_cS")[0].style.display='none';//remove sort box
document.getElementsByClassName("w_ew w_mQ")[0].style.display='none';//remove other cam invite
document.getElementsByClassName("panel e_r e_P")[0].style.display='none';//remove remove topics
document.getElementsByClassName("panel z_r z_R")[0].style.display='none';//remove similar stories box
document.querySelector('ul.C_fB').style.display='none';//remove explore button
document.querySelector('.buttons').style.display='none';//remove login and signup
document.getElementsByClassName("clearfix aJ_S aJ_eP")[0].style.display='none';//remove author bio
document.getElementsByClassName("clearfix aE_lt")[0].style.display='none';//remove comment field
document.getElementsByClassName("be_eB")[0].style.display='none';//remove literotica live link
document.getElementById('mainFooter').style.display='none';//remove footer panel
